### ISSUE TITLE
the libraries are in the root folder

### ISSUE THREAD

**Issue by SubodhChettri** [patdaburu/lambda-layer#4]
According to the [aws docs](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path) the python libraries needs to be under the python folder or python/lib/python**_<version>_**/site-packages. I am guessing best bet would be to put under **python** folder.

**Comment by SubodhChettri** [comment]
changing the line[212 ](https://github.com/patdaburu/lambda-layer/blob/3e1f1dc8c613588daa7f90b2c4677e0e110fd784/lambda_layer/package/bash.py#L212) to would fix the problem
`arcname = "/python"+path[site_packages_len:]`

**Comment by patdaburu** [comment]
Many thanks for this information!  I will look into the change you suggested.

**Comment by SubodhChettri** [comment]
Thanks @patdaburu. Eagerly waiting for the fix.

**Comment by patdaburu** [comment]
Thank you again, @SubodhChettri.  I truly appreciate your insight!  I've sent you an invitation to the repository.

**Comment by patdaburu** [comment]
Merged the change.  Thank you again @SubodhChettri!
